language: python
python:
- 'pypy3.5'
- '3.7'
- '3.6'
- '3.5'
- '2.7'
sudo: false
install:
- pip install -U pip
- pip install -U pytest
before_script:
- pip install -r requirements-test.txt
script:
- python ./setup.py develop
- pytest tests/*
deploy:
  provider: pypi
  user: davidlday
  distributions: sdist bdist_wheel
  on:
    python: '3.7'
    tags: true
