language: python
python:
- 'pypy3.5'
- '3.7'
- '3.6'
- '3.5'
- '2.7'
sudo: false
install:
- pip install -U pip
- pip install -U pytest
before_script:
- pip install -r requirements-test.txt
script:
- python ./setup.py develop
- pytest tests/*
deploy:
  provider: pypi
  user: davidlday
  distributions: sdist bdist_wheel
  password:
    secure: QA1A0VkQsqEifBUFqy9gonPcc2CDoGWsTGdYExyUUeOy2gzUj0xk3/7slojQgLhnn53/t0G2y6rEfN0x+AZLX1C/RhFy8aWDAJNjNBD5qkYuWeXPO+sWf9yblrs9q3jQN0ninO92IgVqN2LrRbX3acL5yFP8PDTAFRAXegxiCrr84QzjC84QBfC1vS7bRNejgGKQl2eIbvNB5XvAkkQTmiBnRLpYaczlfvDBfTGWGLv5ha2sDkiuXjVWSrQyXpRgTn+VhB2X3kYQl0xjXRvMfhvBMTnKtXxwM1IamkgsoinzguMMXSjcI+PBAsVRRv4zZNaqyapvqw+MrH+lwOUE3nIfuRwScTD9wtxwnnmMvovElUS5yL2T0gdWNzg0SwtxlrIBNwOFp+Xe40rtQAK98FkwJr/5at5TCuvKKbicgPlJx/gyHpKCTNjP9DaVOSK8cj4QAH8mG8/QBo4s+u2Ng8lUu3/Dd+wrBSHESYh96nJLHhxHCXSVXlnFODSXS79vPtvoCQfa1S4ByZXjsNFi2pplThc5P+DFw6O0GmCf1kHFxLKOZ5cpk9lVqBRuQxt1Kcfd3STArdCH7+tKE4KDJIFJ2CpIpm/9migaRRuQzS1RGmgoPSXTQYYcsjJAyJyIOJ/AQIF//4YRP0Qmt3ktBhZ/deZGfUicYCEw9VgUBhQ=
  on:
    python: '3.7'
    tags: true
