name: Publish to PyPi

on:
  push:
    tags:
      - "v*"

concurrency:
  group: pypi-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: prosegrinder/.github/.github/workflows/poetry-ci.yaml@main

  publish:
    needs: ci
    uses: prosegrinder/.github/.github/workflows/poetry-publish.yaml@main
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
