name: Publish to PyPi

on:
  push:
    tags:
      - "v*"

concurrency:
  group: pypi-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    if: github.ref == 'refs/heads/main'
    uses: prosegrinder/.github/.github/workflows/poetry-ci.yaml@main
    secrets:
      VERSION_BUMP_TAG_TOKEN: "${{ secrets.VERSION_BUMP_TAG_TOKEN }}"

  publish:
    if: github.ref == 'refs/heads/main'
    needs: ci
    uses: prosegrinder/.github/.github/workflows/poetry-publish.yaml@main
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
