name: Bump Version and Create Release

on:
  push:
    branches:
      - main

concurrency:
  group: tag-and-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.ref, 'refs/tags/v')"
    # Don't run on tags
    needs: ci
    uses: prosegrinder/.github/.github/workflows/poetry-release.yaml@main
    secrets:
      VERSION_BUMP_TAG_TOKEN: "${{ secrets.VERSION_BUMP_TAG_TOKEN }}"
